# Generated by Django 6.1 on 2026-08-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=120)),
                ('district', models.CharField(db_index=True, max_length=120)),
            ],
            options={
                'ordering': ('state', 'district'),
                'constraints': [models.UniqueConstraint(fields=('state', 'district'), name='unique_state_district')],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='institutions.location')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
