# Generated by Django 6.1 on 2026-08-25 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('WASTE_MANAGEMENT', 'Waste Management'), ('WATER_CONSERVATION', 'Water Conservation'), ('ENERGY', 'Energy'), ('PLANTATION', 'Plantation'), ('CLEANLINESS', 'Cleanliness'), ('TRANSPORT', 'Transport'), ('AWARENESS', 'Awareness')], db_index=True, max_length=30)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, max_length=10)),
                ('eco_points', models.PositiveIntegerField()),
                ('requires_proof', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ActivityCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('ACTIVITY', 'Activity'), ('DAILY_ACTIVITY', 'Daily Activity'), ('CAMPAIGN', 'Campaign')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='activity_proofs/')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('submission_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
