# Generated by Django 6.1 on 2026-08-25 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitycompletion',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activitycompletion',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='activitycompletion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_activity_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='activities.activity'),
        ),
        migrations.AddConstraint(
            model_name='activitycompletion',
            constraint=models.UniqueConstraint(fields=('student', 'activity', 'date'), name='unique_activity_completion_per_day'),
        ),
        migrations.AddConstraint(
            model_name='activitycompletion',
            constraint=models.UniqueConstraint(fields=('student', 'campaign', 'date'), name='unique_campaign_completion_per_day'),
        ),
    ]
