# Generated by Django 6.1 on 2026-08-25 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignsubmission',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignsubmission',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_campaign_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
