# Generated by Django 6.1 on 2026-08-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('criteria_type', models.CharField(choices=[('ACTIVITY_COUNT', 'Activity Count'), ('CURRENT_STREAK', 'Current Streak'), ('CATEGORY_COUNT', 'Category Count'), ('QUIZ_COUNT', 'Quiz Count'), ('CAMPAIGN_COUNT', 'Campaign Count'), ('ECO_POINTS', 'Eco Points')], max_length=30)),
                ('criteria_value', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('criteria_value', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('ACTIVITY', 'Activity'), ('QUIZ', 'Quiz'), ('CAMPAIGN', 'Campaign')], max_length=20)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-awarded_at',),
            },
        ),
    ]
